pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: php -l simple-app/src/index.php
  displayName: 'check PHP syntax'

- task: CopyFiles@2
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    targetFolder: $(Build.ArtifactStagingDirectory)
    contents: |
      simple-app/**/*
      !.git/**/*

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
